controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
restricted:
    path: /restricted
    controller: App\Controller\RestrictedController::index