parameters:
    image_directory: '%kernel.project_dir%/public/uploads/images'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $clientId: '%env(PAYPAL_CLIENT_ID)%'
            $clientSecret: '%env(PAYPAL_CLIENT_SECRET)%'
            $baseUrl: '%env(PAYPAL_BASE_URL)%'

    # Registering specific services
    App\Twig\Extension\ModelsExtension:
        arguments:
            $modelsRepository: '@App\Repository\ModelsRepository'
        tags:
            - { name: twig.extension }

    # Register PayPalService with specific arguments
    App\Service\PayPalService:
        arguments:
            $client: '@http_client'

    # Register all services in src/ except specified exclusions
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Twig/Extension/'
